### ISSUE TITLE
Missing MsQuic Features

### ISSUE THREAD

**Issue by nibanks** [MPK1/quic-explorer#7]
MsQuic officially supports the following, which aren't currently listed on here:

- Cubic
- BBRv1
- QUIC v2
- Grease bit
- Datagrams
- OpenSSL (quictls fork) and Schannel TLS libraries

**Comment by MPK1** [comment]
Hi Nick,

thanks for the information! As a frequent and conviced user of MsQuic, I'm kind of aware of that, I simply had no time yet to search the source code for proofs and add the information for all implemenations to the JSON.
The page is currently in a proof-of-work state, so right now there are also only 8 entries for features (https://github.com/MPK1/quic-explorer/blob/main/data/entries.json) which I added to see if displaying and filtering them works as expected 😄

I just added the Grease bit support [here](https://github.com/MPK1/quic-explorer/commit/60162aaee7ccd398a6e77b71aec98fadbc3e9f43) using the [simple cli](https://github.com/MPK1/quic-explorer/blob/main/cli/simple_cli.py).

If you want to want to check out the current workflow and structure of QUIC explorer, feel free to add the remaining 4 features and create a PR with an updated `entries.json`. I would be happy to merge it and receive some feedback!

Otherwise I will add the remaining info (and a new "XDP support" feature) on monday.

Cheers and have fun at the upcoming Hackathon

Marcel
